import type { ModuleConfig } from '../shared/types'

export const MODULES: ModuleConfig[] = [
  {
    id: 'home',
    label: 'Accueil',
    icon: '🏠',
    path: '/',
    minRole: 'commercial',
    loader: () => import('../modules/home'),
  },
  {
    id: 'perflead',
    label: 'PerfLead',
    icon: '🎯',
    path: '/perflead',
    minRole: 'commercial',
    loader: () => import('../modules/perflead'),
  },
  {
    id: 'simulateur',
    label: 'Outils',
    icon: '🧮',
    path: '/simulateur',
    minRole: 'commercial',
    loader: () => import('../modules/simulateur'),
  },
  {
    id: 'admin',
    label: 'Administration',
    icon: '⚙️',
    path: '/admin',
    minRole: 'admin',
    loader: () => import('../modules/admin'),
  },
  {
    id: 'finances',
    label: 'Finances',
    icon: '💶',
    path: '/finances',
    minRole: 'admin',
    loader: () => import('../modules/finances'),
  },
  {
    id: 'annuaire',
    label: 'TessAnnuaire',
    icon: '📚',
    path: '/annuaire',
    minRole: 'admin',
    loader: () => import('../modules/annuaire'),
  },
  {
    id: 'partenaires',
    label: 'Partenaires',
    icon: '🤝',
    path: '/partenaires',
    minRole: 'admin',
    loader: () => import('../modules/partenaires'),
  },
  {
    id: 'conformite',
    label: 'Conformité',
    icon: '🛡️',
    path: '/conformite',
    minRole: 'admin',
    soon: true,
    loader: () => import('../modules/conformite'),
  },
  {
    id: 'fournisseur',
    label: 'Espace fournisseur',
    icon: '◎',
    path: '/fournisseur',
    minRole: 'fournisseur',
    soon: true,
    // Caché de la sidebar — accessible via /perflead/fournisseur uniquement
    hidden: true,
    loader: () => import('../modules/fournisseur'),
  },
]
